### ISSUE TITLE
Import extra python modules

### ISSUE THREAD

**Issue by Ahmed-Elghandour** [TeachBooks/template#1]
in my book, within the interactive Python cell, I was trying to import python module called colorcet
I got this error: ModuleNotFoundError: No module named 'colorcet'

how to make it work for this module or other modules?

**Comment by Tom-van-Woudenberg** [comment]
See https://gitlab.tudelft.nl/interactivetextbooks-citg/jupyter-book-manual/-/merge_requests/50
