### ISSUE TITLE
references do not appear in the References page

### ISSUE THREAD

**Issue by guin0x** [TeachBooks/template#29]
I tried fiddling around a bit with the config file but couldn't fix it. 

If you go to https://teachbooks.github.io/template/main/references.html there are no references there, even though https://github.com/TeachBooks/template/blob/main/book/_config.yml has the `bibtex_files: - references.bib` and https://github.com/TeachBooks/template/blob/main/book/references.bib has a `@misc` reference there.

**Comment by Tom-van-Woudenberg** [comment]
@guin0x, that's because there's no actual reference to the reference in the build pages

**Comment by guin0x** [comment]
just need to use `{cite}`reference``
