### ISSUE TITLE
Exercises: Initial Idea List

### ISSUE THREAD

**Issue by rlanzafame** [TeachBooks/template#36]
The Manual is being revised to facilitate workshops, part of which requires the addition of exercises to the Template, which is used by students during the workshop. [PR 46 in the Manual]( https://github.com/TeachBooks/manual/pull/46) contains a list of ideas, which can be added here when the workshop is completed.

Issues can be used to track ideas for new exercises to create. Label **exercises** is created to help filter Issues.

**Comment by rlanzafame** [comment]
Adding ideas here for exercises for local build:
- a getting started exercise that concisely indicates the preparation steps and where to find them. should be able to complete independently, as this page could be sent as preparation material for a workshop
- include one for the missing pages in the toc that requires a refresh. A second one for when the book needs to be cleaned and rebuilt (e.g., add a bunch of `title: xxx` to existing pages in toc.
- using `teachbooks`: build and serve

**Comment by rlanzafame** [comment]
Freek's exercises, along with a cheat sheet: https://tud-seed.github.io/betasteunpunt/main/JB/Online_werken.html


Other ideas for exercises:
- markdown crash course (key things in one page - e.g., use the things for freek's cheat sheet). could also have them activate a page in the toc that includes a bunch of syntax errors that break the markup, but not the build
- notebook crash course
- cell tag and download link replacer
- debugging challenges: we set up things that break (toc problems, incorrect file names, missing/extra subdirectories in path, etc. need some that break book build, and other that only have missing pages.

**Comment by rlanzafame** [comment]
Can we leave open? I imagined this would collect things post workshop too

**Comment by Tom-van-Woudenberg** [comment]
And added ideas for exercises as separate issues: https://github.com/TeachBooks/template/labels/exercises
